<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>HolyGuards</AssemblyName>
    <RootNamespace>HolyGuards</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(VINTAGE_STORY)/**/*.dll" />
  </ItemGroup>
</Project>
